#
# General config
#
branches:
  only:
  - master
sudo: required
dist: trusty
language: generic

# Enable docker support
services:
- docker

notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
    - secure: "EQ9/ZrsTO2bBr3EReU8msl2XlV68ujQEdWVJdSFH5ZM7O1PxDbGARVVZspSCQcf4AdrZE2U8fMPPEgLp9pLIkMA4phm9wk+0USRzIO2xh+leN0t9Ka18cb4LhMtso5CYBU4OauQj/1D8jtu1tWEhSvW8wI2deVqPHvxdlLo4Cl7OiEBvyDj6jeRy/95fDWoMKYK/WrIWAdSs10kh1bVQecpRjdiD0OxHr8VWvP+6Ext1ZhuJuyHPP2Vui02FrSklA315MaVopVhapd3Oj5vExcmQjTkvO7GItcxwvgUHFinHp0aEhJ/FNkNGhzFnZcz8ijKa0MyrGVctYgZbOrycM1NE2uK/Pvaxc5hTFrAI3Jv+09lI3WD/iAtn59Uub18xJlm1z+4icwcHpFG8ch7jiJ5mIazPoivBoiFaIZLjLt0EB9KsPR1sPY3Y5d3oz8wN2w12gjbBBesIgqrjZvdf5+8WAzQrgV8tRlWidlucvr88bGC2IPO8t61ZKdVAZHSEeBejE5/VExq6RyGga6YUdm/sH7a8kmU2BXIxf3UIuQG03Atx7GMF4nv2XDtdWFkDoTeHQyLbu8mQfFFjbIKrGou3GGXm/I+cA99as9VLbvU+prs0ENBIZVddi8fojX2JqcI9n5f4Fe1ZrSaKBt72vtQ2PI38p8f84/qvT69fRp4="
    - secure: "pSV8JF2LGd0CT6N3CYMrJE5bE2wjmCouKtEEH2NfIhLvkYR0tbB6TcGyKBANkbqXSp4Tvtja+hyRjeOJpabLHXNg9XPy2NkXSvNeGjwB2HVlrwC8EB4TxouP3jQrNRo1Rz+OrPkePhkS2OkMQ9gx8ZFfeYfpUttXGoqZdoIb3k9aUN7VjxQndp/VMO8BiRlmfEt/RmfKjcSJYFs8/+4flT45n63R+3JscuawPIgtg+R0Cl11PcG63Vfn+cBpi4FOlU5A3w7PEfoxQ1swlu3fcv4R174LB7cWh1HHL+Yi81kdxpDhAbjjrUSD+jLjTigkEV9duzHu+NN34g2uBzVZ5p9RW6vAC3YyG5wAy0CphaP92FYfHpOV41uHO0VXfkMvo8Xc+TKZRxsDkzjHzyfOp/RujPR/uvafKdYFqz9PvQSunpandKT+pjWdO8K60UCaE9H2wFEWZUULPGlOejMM2Ke/6V4l0wGrVSBZ3GcrGNOIqO97ML644/p78NB6/mz0AnWeeHOlyZPBRryqYNlZSs9hV2Vo8FLUjG5odE4ppBchUCyGDAnfmZ8kCsuONM+eye4l2jm+iiWPbXeVQ2Ffc2boEBcyMDw+LK9EDZUConJJUyuedwoRbmSvveF5rbEPmKEw5Vpzpst+OVH00cWnN+Ka6KdAGMmimqgzZ/YDtew="

#
# Dependencies
#
addons:
  homebrew:
    packages:
    - coreutils
    - cmake
    - gmp
    - cln
    - ginac
    - boost
    - eigen
    - python
    - python3
    - maven
    update: true # fix for current problem with "unknown command 'bundle'"

#
# Configuration
#
jobs:
  include:
    # osx
    - os: osx
      compiler: clang
      env: TASK=Test PYTHON=python3 CONFIG=DebugClnParser COMPILER=clang STL=libc++
      script: travis/build.sh
    - os: osx
      compiler: clang
      env: TASK=Test PYTHON=python3 CONFIG=Release COMPILER=clang STL=libc++
      script: travis/build.sh
    - os: osx
      compiler: clang
      env: TASK=Test PYTHON=python3 CONFIG=ReleaseCln COMPILER=clang STL=libc++
      script: travis/build.sh
    - os: osx
      compiler: clang
      env: TASK=Test PYTHON=python3 CONFIG=ReleaseClnParser COMPILER=clang STL=libc++
      script: travis/build.sh
    # debian-9
    - os: linux
      compiler: gcc
      env: TASK=Test PYTHON=python3 CONFIG=DebugClnParser LINUX=debian-9 COMPILER=gcc
      script: travis/build.sh
    - os: linux
      compiler: gcc
      env: TASK=Test PYTHON=python3 CONFIG=ReleaseClnParser LINUX=debian-9 COMPILER=gcc
      script: travis/build.sh
    # ubuntu-18.04
    - os: linux
      compiler: gcc
      env: TASK=Test PYTHON=python3 CONFIG=DebugClnParser LINUX=ubuntu-18.04 COMPILER=gcc
      script: travis/build.sh
    - os: linux
      compiler: gcc
      env: TASK=Test PYTHON=python3 CONFIG=ReleaseClnParser LINUX=ubuntu-18.04 COMPILER=gcc
      script: travis/build.sh
    # debian-10
    - os: linux
      compiler: gcc
      env: TASK=Test PYTHON=python3 CONFIG=DebugClnParser LINUX=debian-10 COMPILER=gcc
      script: travis/build.sh
    - os: linux
      compiler: gcc
      env: TASK=Test PYTHON=python3 CONFIG=ReleaseClnParser LINUX=debian-10 COMPILER=gcc
      script: travis/build.sh
    # ubuntu-19.10
    - os: linux
      compiler: gcc
      env: TASK=Test PYTHON=python3 CONFIG=DebugClnParser LINUX=ubuntu-19.10 COMPILER=gcc
      script: travis/build.sh
    - os: linux
      compiler: gcc
      env: TASK=Test PYTHON=python3 CONFIG=ReleaseClnParser LINUX=ubuntu-19.10 COMPILER=gcc
      script: travis/build.sh
    # ubuntu-20.04
    - os: linux
      compiler: gcc
      env: TASK=Test PYTHON=python3 CONFIG=DebugClnParser LINUX=ubuntu-20.04 COMPILER=gcc
      script: travis/build.sh
    - os: linux
      compiler: gcc
      env: TASK=Test PYTHON=python3 CONFIG=Release LINUX=ubuntu-20.04 COMPILER=gcc
      script: travis/build.sh
    - os: linux
      compiler: gcc
      env: TASK=Test PYTHON=python3 CONFIG=ReleaseCln LINUX=ubuntu-20.04 COMPILER=gcc
      script: travis/build.sh
    - os: linux
      compiler: gcc
      env: TASK=Test PYTHON=python3 CONFIG=ReleaseClnParser LINUX=ubuntu-20.04 COMPILER=gcc
      script: travis/build.sh
    # Documentation
    - os: linux
      compiler: gcc
      env: TASK=Documentation PYTHON=python3 CONFIG=ReleaseClnParser LINUX=ubuntu-20.04 COMPILER=gcc
      script: travis/build.sh
      before_deploy:
        docker cp pycarl:/opt/pycarl/. .
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: doc/build/html/
        on:
          branch: master

  # Allow failures with Debian 9 for now
  allow_failures:
    - os: linux
      env: TASK=Test PYTHON=python3 CONFIG=DebugClnParser LINUX=debian-9 COMPILER=gcc
    - os: linux
      env: TASK=Test PYTHON=python3 CONFIG=ReleaseClnParser LINUX=debian-9 COMPILER=gcc
