#
# General config
#
branches:
  only:
  - master
dist: trusty
language: generic
sudo: required

#
# Configurations
#
jobs:
  include:

    # Linux
    - os: linux
      compiler: gcc
      env: BUILD=DefaultDebug COMPILER=gcc-default PYTHON=python
      install: export OS=linux; export COMPILER='gcc-default'; export PYTHON='python';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-default'; export PYTHON='python';
        travis/build.sh DefaultDebug
    # Mac OS X
    - os: osx
      compiler: clang
      env: BUILD=DefaultDebug COMPILER=clang-default PYTHON=python STL=libc++
      install: export OS=osx; export COMPILER='clang-default'; export STL='libc++'; export PYTHON='python';
        travis/install_osx.sh
      script: export OS=osx; export COMPILER='clang-default'; export STL='libc++'; export PYTHON='python';
        travis/build.sh DefaultDebug
