#
# General config
#
branches:
  only:
  - master
sudo: required
dist: trusty
language: generic

# Enable docker support
services:
- docker

notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
    - secure: "QEKHoyya6CiCt2C8d2TupExTUy24tb8JxYUGVgBm2vqcWaEMuOpVbGeSFUJ9DVsg7VGDcL7rTFGjAJ+AlQLpRP+QKdHidECqbBn17P6koIuSrGuE9Q9VX9GEDiutYjWN8ex2Vx/tgzW7eVV71YdkWfwbnjbXTw4Uf4KqF91yoMLvubAJCaRqjrmnlyd4TWZmi+jxVHaev6OjJ82j1lCKWqNd11PpQMVWMyKE0AqX87P6fcnm5lFgV/8sK++pOR+j4eJpKeZfaUBa7PxFVIKEzEwjU3B9CKy59Mv5+omLm+56zoiLFy+2kBzdJZN96c/V4gcbO3qwItRixromj8mi0PcldAT2pvEmg50Z6/HHhVIRBiiqJo2CvAwUfp/UCRccx03GJPvzLol/DomArvVWiXHhf5HeNcgMTJ0eeeBZh35KITcltaZpR4+Zdxv+sy/M1AH3Ia0NFPcDZ8+XcR1dZUvNWs14J57gVkzocxDyXVL5CmL07qeyj9eUKLyvWer08TbY1XPpYQBxq9EuV4ZplhEYsHg0c6bMAc7PQIMWmaiVNCuzFb/ws/eTF7MUmbYoMHU3Veva/pf0HQESyoMucA+zXDk5MWJ6VRnYtVRMRdLtsfod9dSfgMNUi+TXNb3ZxjG1KNa9SnvBK+9RJ3hTnpIm9vN7lw84lxv1joElmUw="
    - secure: "V+e+fWWLx/SmFeseTdMvtdu3l/jFUH1SuOXYQXxyXeHcyofp/plxT5k+3ZWuCm2w3o9J9zSXo8qSFlcUR0KkSOi6moj5ki8mPjiKPbVQEnrXprZ7eVIPf1n9XF2LEON0BIlrh+PbDK5nRtPiW80nbg5UXFO+SnQr5YQgS49VPMqRIP7waIxG5Ha5AEjLXJocbPi0kFD1YBMSaL5mZ3EiGn4edXwdGjDvDhT2mw2gUlD3DQiT8MCpL6Tymt9sMK2fekhcyq7Vx4j1sDzz4X2KQZ0VpYfX+LgqtzmmJl9sd4is90tk5xV2hoxpoEePAUOg3409As0ZwadSgIrU6jLRB8TBZxZB9dcVwp++ZvjmFaHRkBr+p1rQKiiDU+K4SVWrzOtYKsKnhA8bu6TxBxfV7RQ9VPgei7JNJwjhDasWqyoASc6F8/6N03XnDsumZDiGoW6VJh9Ll3gszwqGb/+N1q9zAt1DrQSgI5BYkTjKqqavfxbxzL6ZCYl8ifu6259w45zWVygfhntT7Oe+TB9Sk3Yf9bT+XOIYPkqREFUUEi+DJtvokfJZzL1dVDrbod0vPa4rnmUdKIA2sNjlompb9d3toJlVTprJiDD2fV5DNWk4XYLxG8QvDSUUQY16BfRx2RVbG68kZzXCASdws8JeArI/FZwxyUyohv+9V4namuY="

#
# Configurations
#
jobs:
  include:
    # osx
    - os: osx
      compiler: clang
      env: TASK=Test PYTHON=python3 CONFIG=Release COMPILER=clang STL=libc++
      install: travis/install_osx.sh
      script: travis/build.sh
      after_failure:
        - find . -name "*err*.log" -type f -print -exec cat {} \;
    - os: osx
      compiler: clang
      env: TASK=Test PYTHON=python3 CONFIG=ReleaseCln COMPILER=clang STL=libc++
      install: travis/install_osx.sh
      script: travis/build.sh
      after_failure:
        - find . -name "*err*.log" -type f -print -exec cat {} \;
    - os: osx
      compiler: clang
      env: TASK=Test PYTHON=python3 CONFIG=ReleaseClnParser COMPILER=clang STL=libc++
      install: travis/install_osx.sh
      script: travis/build.sh
      after_failure:
        - find . -name "*err*.log" -type f -print -exec cat {} \;
    # ubuntu-16.10
    - os: linux
      compiler: gcc
      env: TASK=Test PYTHON=python3 CONFIG=Release LINUX=ubuntu-16.10 COMPILER=gcc
      install: travis/install_linux.sh
      script: travis/build.sh
      after_failure:
        - find . -name "*err*.log" -type f -print -exec cat {} \;
    - os: linux
      compiler: gcc
      env: TASK=Test PYTHON=python3 CONFIG=ReleaseCln LINUX=ubuntu-16.10 COMPILER=gcc
      install: travis/install_linux.sh
      script: travis/build.sh
      after_failure:
        - find . -name "*err*.log" -type f -print -exec cat {} \;
    - os: linux
      compiler: gcc
      env: TASK=Test PYTHON=python3 CONFIG=ReleaseClnParser LINUX=ubuntu-16.10 COMPILER=gcc
      install: travis/install_linux.sh
      script: travis/build.sh
      after_failure:
        - find . -name "*err*.log" -type f -print -exec cat {} \;
    # Documentation
    - os: osx
      compiler: clang
      env: TASK=Documentation PYTHON=python3 CONFIG=ReleaseClnParser COMPILER=clang STL=libc++
      install: travis/install_osx.sh
      script: travis/build.sh
      after_failure:
        - find . -name "*err*.log" -type f -print -exec cat {} \;
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: doc/build/html/
        on:
          branch: master

