#
# General config
#
branches:
  only:
  - master
dist: trusty
language: generic

#
# Configurations
#
jobs:
  include:

    # Linux
    - os: linux
      compiler: gcc
      env: BUILD=DefaultDebug COMPILER=gcc-6 PYTHON=python3.4
      install: export OS=linux; export COMPILER='gcc-6'; export PYTHON='python3.4';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export PYTHON='python3.4';
        travis/build.sh DefaultDebug
    # Mac OS X
    - stage: Build dependencies
      os: osx
      compiler: clang
      env: BUILD=DefaultDebug COMPILER=clang-4.0 PYTHON=python3.4 STL=libc++
      install: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++'; export PYTHON='python3.4';
        travis/install_osx.sh
      script: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++'; export PYTHON='python3.4';
        travis/build.sh DefaultDebug
